version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,127.0.0.1
    volumes:
      - .:/app
    command: uvicorn src.server.main:app --host 0.0.0.0 --port 8000 --reload
